# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 136c2f47b934e6c9929d82192f178e0cb120b25e004fd519d87ddb851fad5d2e35e07a33822d7e9a00efa54086c83eca8609cbd4e6b99bd35d72c36f9833561d

test:
  secret_key_base: a94c81e036c1e68e4fa1fb33fc23898960f3592e07b7339232a4c985fc97468e1064055d0f4b288bd54b6c1da409e3601f752ed3764b19a188fe89d24e3c9774

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
